apiVersion: v1 #VERSIÓN DE LA API DEL CHART # OBLIGATARIO
name: yamin-service # NOMBRE DEL CHART # OBLIGATARIO
version: 0.0.1 #VERSIÓN DE CHART #OBLIGATORIO
appVersion: 0.0.1 #VERSIÓN DE LA APP QUE CONTIENE ESTE CHART # MUY RECOMENDABLE
home: https://github.com/feeernando/yamin-service
description: A Helm chart for running yamin-service on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
- fiware
- yamin
sources:
- https://github.com/feeernando/yamin-service
maintainers:
- name: Fernando Muñoz
  email: fermunozmoyano5@gmail.com
  