apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      name: broker
  template:
    metadata:
      labels:
        name: broker
    spec:
      containers:
      - name: mongo
        image: waziup/mongodb:latest
        args: ["--nojournal"]
        ports:
        - containerPort: 27017

      - name: orion
        image: waziup/orion:latest
        ports:
        - containerPort: 1026
        args: ["-dbhost", "localhost:27017", "-logLevel", "INFO"]
       
      - name: fiware-orion
        image: fiware/orion:${ORION_VERSION}
        ports:
        - containerPort: 1026
        args: ["-dbhost", "localhost:27017", "-logLevel", "INFO"]

      - name: cygnus
        image: waziup/cygnus:latest
        ports:
        - containerPort: 8081
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    name: broker
spec:
  type: LoadBalancer
  ports:
  - port: 1026
    targetPort: 8026
  selector:
    name: broker
      
